### ISSUE TITLE
Allow for leading 0 in mod names

### ISSUE THREAD

**Issue by swlody** [remi-dupre/aoc#11]
It would be nice to allow for a leading 0 in mod names (e.g. day01 instead of day1) so that days 10-19 aren't sorted after day1 and days 20-25 aren't sorted after day2.

In other words currently I'm forced to have:

```rust
mod day01;
mod day10;
mod day11;
// ...
mod day19;
mod day2;
mod day20;
// ...
mod day25;
mod day3;
```

whereas I'd like to be able to do:

```rust
mod day01;
mod day02
mod day03;
// ...
mod day10;
mod day11;
mod day12;
```

etc.

**Comment by IceSentry** [comment]
You can already do that, you just have to pass it 01 instead of 1, the macro doesn't car as long as it's a valid integer. You could even do 001 if you wanted.

**Comment by remi-dupre** [comment]
It could still be interesting to get a better error message (and eventually get more robust, but I'm not sure if that last on wouldn't be annoying).

**Comment by swlody** [comment]
Not really sure why I thought this didn't work, maybe it didn't work in a previous version?

**Comment by remi-dupre** [comment]
That's possible as I rewrote most of the parsing mechanism [here](https://github.com/remi-dupre/aoc/pull/8)
