### ISSUE TITLE
[Suggestion] change output color to work better on windows with vscode

### ISSUE THREAD

**Issue by IceSentry** [remi-dupre/aoc#13]
For some reason on windows 10 in the vscode terminal .dimmed() doesn't work, it's most likely an issue with colored but a potential workaround could be to use .bright_black() instead since it's very close to what .dimmed() outputs.

in vscode

![image](https://user-images.githubusercontent.com/8348954/101932730-3afb6d80-3ba9-11eb-9211-d268c57a2efa.png)

First one is using .bright_black, second one is using .dimmed

Here it is in the windows terminal, again first one is using bright_black, second one is using dimmed

![image](https://user-images.githubusercontent.com/8348954/101932845-62ead100-3ba9-11eb-9339-8c313a7f6c32.png)

I can make a PR if you want

**Comment by remi-dupre** [comment]
It would be awesome if you could do a PR as I can't easily experiment on windows :)
