### ISSUE TITLE
Allow use of `-d`  for benchmarks

### ISSUE THREAD

**Issue by ThomasdenH** [remi-dupre/aoc#18]
Benchmarks take a long time to run, so it's useful to select a single day to run. However, currently I get the following error:
```rust
error: Found argument '--day' which wasn't expected, or isn't valid in this context
```

I made a [fork](https://github.com/ThomasdenH/aoc) that basically has this functionality, but I'm unsure why the error occurs (presumably it originates from clap?).

**Comment by frobiac** [comment]
Nice idea! Regarding the clap error I submitted a PR #17 yesterday

**Comment by ThomasdenH** [comment]
That was indeed the problem! I have opened a PR with my code.

I noticed that removing the line also meant no colors would be produced, in other words that `configure_from_args` changes `Criterion` even when no args are supplied. I opened a PR: https://github.com/bheisler/criterion.rs/issues/537
