### ISSUE TITLE
.token file should not be stored in project directory

### ISSUE THREAD

**Issue by swlody** [remi-dupre/aoc#2]
I think it's unexpected behavior to store the .token file in the project directory. I personally didn't notice that it was there and accidentally committed and pushed it. I know accidentally leaking the session cookie for adventofcode.com isn't a huge security concern, but it would still be better to store the token in an external config directory, using e.g. https://docs.rs/dirs/3.0.1/dirs/fn.config_dir.html

At the very least, it would be nice to have some warning in the README to add .token to the .gitignore file.

**Comment by remi-dupre** [comment]
That's a very nice suggestion (I had the same issue but didn't think about how to fix it yet), `config_dir` seems like a fair way to go. (it would add another dependency but it seems quite tiny, and as long as I don't add a feature to deactivate Criterion I can't pretend that we are cautious about heavy dependencies...)
