### ISSUE TITLE
Allow for `Result` or `Option` outputs

### ISSUE THREAD

**Issue by remi-dupre** [remi-dupre/aoc#4]
From a [reddit suggestion](https://www.reddit.com/r/rust/comments/k8ador/advent_of_code_2020_day_7/geyds8b?utm_source=share&utm_medium=web2x&context=3).

I am not sure how this would be implemented, maybe it would require a proper syntax to indicate that the output needs to be unwrapped, maybe we would reach the limit of using a `macro_rule`.

**Comment by remi-dupre** [comment]
```rust
macro_rules! test {
    (
        year $year: expr;
        $( $day: ident $( : $generator: ident )? => $( $solution: ident $( ? )? ),+ );+
        $( ; )?
    ) => {};
}

test! {
    year 2020;
    day1 : generator => part1?, part2;
}
```

This appears to work fine, I suppose this could be a nice syntax :)

**Comment by WhoisDavid** [comment]
For solvers, have you considered using `Debug` instead of `Display`?

**Comment by remi-dupre** [comment]
> For solvers, have you considered using `Debug` instead of `Display`?

Display seems to be a nice way to go in order to get an inline message for the error:

![Screenshot_2020-12-09_20-40-15](https://user-images.githubusercontent.com/1173464/101678812-c3b9c280-3a5e-11eb-81a9-a1ab32016b26.png)

**Comment by remi-dupre** [comment]
Implemented by #8

**Comment by Silver-Golden** [comment]
Setting up aoc-main for last years aoc and trying to run/compile I get this:

```
   Compiling aoc-2019 v0.1.0 (C:\Dev\WebStorm\Advent of Code\2019)
error[E0277]: `std::option::Option<i32>` doesn't implement `std::fmt::Display`
  --> src\main.rs:6:1
   |
6  | / aoc_main::main! {
7  | |     year 2019;
8  | |     day01 : input_generator => solve_part1, solve_part2;
9  | |     day02 : input_generator => solve_part1, solve_part2;
10 | |     day03 : input_generator => solve_part1, solve_part2;
11 | |     day04 : input_generator => solve_part1, solve_part2;
12 | | }
   | |_^ `std::option::Option<i32>` cannot be formatted with the default formatter
   |
   = help: the trait `std::fmt::Display` is not implemented for `std::option::Option<i32>`
   = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
   = note: required by `std::fmt::Display::fmt`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

```

my cargo.toml is like this:

```toml
[dependencies]
aoc-main = { git = "https://github.com/remi-dupre/aoc.git", branch = "main" }
```

It is a fresh install so it aught to be getting the latest changes, including #8

**Comment by remi-dupre** [comment]
Hi @Silver-Golden!

You'd probably want to tell `aoc-main` to unwrap the value by suffixing your solutions returning and `Option` with `?`. I should probably add a line or two about that in the readme ^^

It also makes me wonder how I could allow for something more general than `Display` as results but still keep a pretty output :thinking:

**Comment by swlody** [comment]
I agree that it would be nice to at least have the option to format using Debug instead of Display. Using Display makes it impossible to return tuples for example, which I found necessary for this year's day 9, meaning I needed to manually create a new struct and implement display for it to get everything working:

```rust
pub struct Answer(u64, u64);

use std::fmt;
impl fmt::Display for Answer {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Part 1: {}, Part 2: {}", self.0, self.1)
    }
}

pub fn solve_both_parts(input: &[u64]) -> Answer {
    let part1_result = solve_part1_with_preamble_length(input, 25);
    let part2_result = solve_part2_from_part1(input, part1_result);
    Answer(part1_result, part2_result)
}
```

vs. just:

```rust
pub fn solve_both_parts(input: &[u64]) -> (u64, u64) {
    let part1_result = solve_part1_with_preamble_length(input, 25);
    let part2_result = solve_part2_from_part1(input, part1_result);
    (part1_result, part2_result)
}
```
