### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by j2ghz** [remi-dupre/aoc#6]
A crate with the same name already exists https://crates.io/crates/aoc, so I don't know if you published it under a different name or not. If you don't want to publish (yet), it might be a good idea to have that stated in the readme.

**Comment by remi-dupre** [comment]
What would you think about `aoc-main`?

**Comment by j2ghz** [comment]
sounds good, or `aoc-macro`

**Comment by remi-dupre** [comment]
:tada: https://crates.io/crates/aoc-main :tada:

I'll just have to rename the repo someday ^^
